name: Build Container Images

on:
  workflow_dispatch: # 手动在 GitHub Actions 页面点击运行
  push:
    tags:
      - 'v*.*.*'

env:
  GHCR_REPO: ghcr.io/Wick6603/joplin-server

jobs:
  build:
    strategy:
      matrix:
        platform: [ linux/arm64]
        include:
          - platform: linux/arm64
            os: ubuntu-24.04-arm
            dockerfile: ./joplin/Dockerfile.server
            #dockerfile: ./joplin-arm-fix/Dockerfile.server
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set version based on tag
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          
      - name: Checkout Joplin Server
        uses: actions/checkout@v6
        with:
          repository: Wick6603/joplin
          ref: server-${{ env.RELEASE_VERSION }}
          path: joplin

      #- name: Checkout Joplin Server ARM fix
      #  if: matrix.platform == 'linux/arm64'
      #  uses: actions/checkout@v6
      #  with:
      #    repository: etechonomy/joplin-arm-fix
      #    path: joplin-arm-fix
      #    token: ${{ secrets.GH_PAT }}}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./joplin/
          file: ./${{ matrix.dockerfile }}
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          platforms: linux/arm
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true

     
